on: [push]

jobs:
  increment-pixela-graph:
    runs-on: ubuntu-latest
    name: Invoke Pixela increment webhook
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Invoke webhook
        uses: ./
        id: increment-pixela
        with:
          username: ${{ secrets.PIXELA_USERNAME }}
          token: ${{ secrets.PIXELA_TOKEN }}
          webhook_hash: ${{ secrets.PIXELA_WEBHOOK_HASH }}
